#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Sensor, S4,     HighCol,        sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "helper.h"


void dropWater_L(){
	displayBigStringAt(50,50,"water");
	stopRobot();

	moveTank(1 ,20 ,-20 ,270);


	stopRobot();


	//at table
	moveForward(3, 20, 50);
	moveRack(20, 400);
	wait1Msec(100);
	moveForward(3, -20, 65);
	moveRack(-20, 500);
	stopRobot();
	moveForward(3, -30, 65);
	stopRobot();
	wait1Msec(100);
	moveTank(1, -20, 20, 320);

	//goto laundry

	moveForward(3, -20, 140);

	stopRobot();
	setMotorSpeed(clawArm, -50);
	wait1Msec(1500);
	moveTank(1, -20, 20, 200);
	stopRobot()
	moveForward(3, 30, 150);
	stopRobot()
	wait1Msec(300);
	setMotorSpeed(clawArm, 80);
	wait1Msec(1700);
	stopRobot();


	////Turn to go bACK HOMEE
	moveForward(3, -30, 130);
	moveTank(1, 20, -20, 180);



};
