#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//setMotorSpeed(armMotor, -50);
	//wait1Msec(1000);

	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, -50);
	wait1Msec(200);

	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);
	wait1Msec(600);

	while (getColorReflected(LeftCol)>15)
	{
		setMotorSpeed(leftMotor, 20);
		setMotorSpeed(rightMotor, 20);
	};

	clearTimer(T1);
	while (time1[T1] <3000){
		setMotorSpeed(leftMotor, (getColorReflected(LeftCol)-25)*0.2);
		setMotorSpeed(rightMotor, (getColorReflected(RightCol)-49)*0.2);

	}


	//setMotorSpeed(armMotor, 50);
	//wait1Msec(1000);
	//setMotorSpeed(leftMotor, -50);
	//setMotorSpeed(rightMotor, -50);
	//wait1Msec(100);

	setMotorSpeed(leftMotor, -30);
	setMotorSpeed(rightMotor, 30);
	wait1Msec(600);

while (getColorReflected(LeftCol)>15)
	{
		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
	};

	setMotorSpeed(leftMotor, -30);
	setMotorSpeed(rightMotor, 30);
	wait1Msec(600);

}
