#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "helper.h"
#include "hitechnic-colour-v2.h"
//string colour2;

//tHTCS2 hi2_B;


void playBall_L(){

	displayBigStringAt(50,50,"play ball");
	stopRobot();

	moveTank(1, 20, -20, 30);
	moveForward(3, 20, 140);
	stopRobot();


	//turn to and pickup ball


	moveTank(1, -20, 20, 150);
	moveForward(3, 20, 25);
	moveTank(3, -5, 5, 16);
	stopRobot();
	moveTank(2, -5, 5, 15);
	moveTank(1, -5, 5, 10);
	moveForward(3, -10, 20);

	moveClaw(-50, 2000);
	stopRobot();

	moveForward(5, 5, 6.2);

	moveClaw(100, 1500);
	stopRobot();
	moveForward(3, -20, 70);

	//turn to drop ball

	moveTank(1, 20, -20, 275);
	moveForward(3, 20, 90);
	stopRobot();

	moveClaw(-40, 1500);
	stopRobot();
	wait1Msec(100);

	moveClaw(40, 1600);
	stopRobot();
	moveForward(3, -20, 40);



	//go to pick laundry

	moveTank(1, -20, 20, 130);
	moveForward(3, -30, 300);

	moveForward(3, -20, 100);

	moveClaw(-50, 1800);
	stopRobot();
	moveTank(1, -20, 20, 180);
	stopRobot();

	moveForward(3, 20, 170);
	stopRobot();
	moveClaw(80, 1400);
	stopRobot();

	//cha cha to line!!

	moveTank(1, 20, -20, 150);
		moveForward(3, -30, 170);






}
