#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "helper.h"


void playBall2_L(){


	moveForward(1, -20, 30);
	moveForward(3, -20, 50);
	lineSquare(3000, 40, 0.2);
	moveForward(5, 20, 33);

	moveTank(1, 20, -20, 30);
	moveForward(4, 20, 40);
	stopRobot();
	moveForward(3, 20, 80);

	//turn to and pickup ball


	moveTank(1, -20, 20, 150);
	moveForward(3, 20, 25);
	moveTank(3, -5, 5, 16);
	stopRobot();
	moveTank(2, -5, 5, 12);
	moveForward(3, -10, 10);
	setMotorSpeed(clawArm, -50);
	wait1Msec(2000);
	stopRobot();
//	//STUCK HERE FIX MEEEE!!
	moveForward(5, 5, 4.5);
	setMotorSpeed(clawArm, 100);
	wait1Msec(1200);
	stopRobot();
	moveForward(3, -20, 70);

	//turn to drop ball

	moveTank(1, 20, -20, 275);
	moveForward(3, 20, 20);
	stopRobot();
	setMotorSpeed(clawArm, -40);
	wait1Msec(1500);
stopRobot();
wait1Msec(500);
	setMotorSpeed(clawArm, 40);
	wait1Msec(1500);
stopRobot();
	moveForward(3, -20, 40);



	//go to pick laundry

	moveTank(1, -20, 20, 130);
	moveForward(3, -20, 300);
	moveForward(1, -10, 45);
	moveForward(3, -20, 100);



	setMotorSpeed(clawArm, -50);
	wait1Msec(1900);
	stopRobot();
	moveTank(1, -20, 20, 200);
	stopRobot();

	moveForward(3, 20, 170);
	stopRobot();
	wait1Msec(1000);
	setMotorSpeed(clawArm, 80);
	wait1Msec(1000);
	stopRobot();

	//cha cha to line!!

	moveTank(1, 20, -20, 180);
	moveForward(2, -20, 1000);
	moveForward(1, -20, 16);




}
