#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "hitechDepend\hitechnic-colour-v2.h"
tHTCS2 hi2;

#include "helpers\navHelper.h"
#include "helpers\mechHelper.h"
#include "gameRoutines\dropWater_L.c"
#include "gameRoutines\dropWater.c"
#include "gameRoutines\pickWater.c"
#include "gameRoutines\laundryBasket.c"
#include "gameRoutines\twoRoom.c"




task main()
{
	//pickWater();


	//moveForward(3, -30, 780);
	//moveTank(1, 0, 20, 500)
	//moveForward(3, 30, 100);
	//moveTank_col(1, 0, 10, 20);
	//moveTank_col(2, 20, 0, 23)
	//stopRobot();
	//plf_dist(0, 900, 20, 45, 0.2);
	//plf_col(LeftCol, RightCol, 20, 45, 0.2, 20, 1);

 // runBlueRed_1();


	//moveForward(3, 30, 350);
	//moveForward(1, 30, 30);
	//moveForward(3, 30, 50);


	//moveTank_col(1, 0, 10, 20);
	//moveTank_col(2, 10, 0, 23);

	//plf_dist(0, 500, 20, 45, 0.2);
	//plf_col(LeftCol, RightCol, 20, 45, 0.2, 20, 1);
	//wait1Msec(200);
	//moveForward(3, -20, 20);






	//stopRobot();


 //	runBlueRed_2();

	plf_double(10000, 220, 0.2)


}
