#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "hitechnic-colour-v2.h"
tHTCS2 hi2;

#include "helper.h"
#include "dropWater_L.c"
#include "dropWater.c"
#include "playBall_L.c"
#include "playBall.c"
#include "pickWater.c"
#include "laundryBasket.c"
#include "runBlueRed_1.c"
#include "runBlueRed_2.c"



task main()
{



//pickWater();


//	moveForward(3, -30, 780);
//	moveTank(1, 0, 35, 530);
//	moveRack(20, 1000);
//	moveForward(3, 10, 130);
//	moveRack(-20, 1000);
//	moveTank_col(1, 0, 20, 20);
//	moveTank_col(2, 20, 0, 23)
//	stopRobot();
//	plf_dist(0, 900, 30, 45, 0.2);
//	plf_col(LeftCol, RightCol, 20, 45, 0.2, 20, 1);

//  runBlueRed_1();


//	moveForward(3, 30, 300);
//	moveForward(1, 30, 20);
//	moveForward(3, 30, 70);


//	moveTank_col(1, 0, 20, 20);
//	moveTank(3, 30, 0, 30);
//	moveTank_col(2, 20, 0, 23);

//	plf_dist(0, 500, 20, 45, 0.2);
//	plf_col(LeftCol, RightCol, 20, 45, 0.2, 20, 1);








//	stopRobot();


// 	runBlueRed_2();
//	moveForward(3, -30, 50);
//	moveRack(20, 1500);

	plf_double(10000, 100, 0.4)
}
