#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "hitechnic-colour-v2.h"
tHTCS2 hi2;

#include "helper.h"
#include "dropWater_L.c"
#include "dropWater.c"
#include "playBall_L.c"
#include "playBall.c"
#include "pickWater.c"
#include "laundryBasket.c"

int col;
int marker;
string val;





task main()
{


	pickWater();

	moveForward(3, -30, 780);
	moveTank(1, 0, 20, 500)
	moveForward(3, 30, 100);
	moveTank_col(1, 0, 10, 20);
	moveTank_col(2, 20, 0, 23)
	stopRobot();

	plf_dist(0, 900, 20, 45, 0.2);
	plf_col(LeftCol, RightCol, 20, 45, 0.2, 20, 1);

	moveForward(3, 30, 30);
	moveTank(1, -20, 20, 280)
	stopRobot();

	moveRack(-20, 1000);
	wait1Msec(200);

	moveForward(1, -20, 30);
	moveForward(3, -20, 50);
	lineSquare(3000, 40, 0.2);

	moveForward(3, 20, 100);
	initSensor(&hi2, S4);
	while (hi2.red < 10){
		initSensor(&hi2, S4);
		setMotorSpeed(leftMotor, 10);
		setMotorSpeed(rightMotor, 10);
		readSensor(&hi2);
		val = hi2.red;
		displayBigStringAt(50,50,val);
	};
	stopRobot();
	playSound(soundBeepBeep);
	wait1Msec(500);
	moveForward(3, 20, 25);
	readSensor(&hi2);
	marker = hi2.red;

	val = marker;
	displayBigStringAt(50,50,val);

	wait1Msec(500);
	// stary laundry block scan

	moveForward(3, 20, 120);

	stopRobot();
	wait1Msec(1000);

	initSensor(&hi2, S4);

	wait1Msec(500);
	readSensor(&hi2);
	if(hi2.red > 230){
		playSound(soundBeepBeep);
		sleep(200);
		col = 1;
		//yellow detected
	}
	else if(hi2.red > 100 && hi2.red < 220 ){
		playSound(soundBeepBeep);
		playSound(soundBeepBeep);
		sleep(200);
		col = 2;
		//red detected
	}
	else if(hi2.red > 10 && hi2.red < 80 ){
		playSound(soundBeepBeep);
		playSound(soundBeepBeep);
		playSound(soundBeepBeep);
		sleep(200);
		col = 3;
		//black detected
	}
	else {
		col = 0;
		// no laundry
	}

	val = marker;
	displayBigStringAt(50,50,val);

	if (marker > 50 ){
		  if ( col != 0) {
	       dropWater_L();
	    }
	    else { dropWater();}
	  }

	else {
		    if (col != 0){
		      playBall_L();
	         }
	      else{
		      playBall();
	       }
  }

	displayBigStringAt(50,50,"done room task");
	moveTank(1, -20, 20, 300);
	moveForward(3, -30, 1000);
	if(col != 0){
		plf_dist(0, 1500, 40, 45, 0.2);
		stopRobot();
		moveForward(3, 30, 700);
		moveTank(1, 20, -20, 280);
		//Turn face bins
		moveForward(3, 30, 200);
		moveForward(1, 30, 20);
		moveForward(3, -20, 50);
		moveTank(1, 20, -20, 220);
		moveForward(1, 20, 20);
		stopRobot();
		moveForward(3, -20, 20);

		lineSquare(3000, 40, 0.2);
		moveForward(3, -20, 200);
	}

	else{
		//dont do laundry
	};

	laundryBasket(col);

		moveTank(1, -20, 20, 280);
  	moveForward(3, 10, 20);
  	moveClaw(-50, 2000);

}
