#pragma config(Sensor, S1,     LeftCol,        sensorEV3_Color)
#pragma config(Sensor, S2,     Ultra,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     RightCol,       sensorEV3_Color)
#pragma config(Motor,  motorA,          rackArm,       tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Medium, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorD,          clawArm,       tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "helper.h"

//  	plf_col(int sensefollow, int stopsense, int speed, int mid, float kp, int stopat, int types);
//  	plf_dist(int s, int dist, int speed, int mid, float kp);
//		plf_ultra(int sens, int dist, int speed, int mid, float kp);
//		lineSquare(int sec, int mid, float sens)


task main()
{

	plf_dist(0, 1000, 20, 45, 0.2);

}
